08_Routes_Cont_Views/games_on_rails/config/routes.rb
GamingApp::Application.routes.draw do
  root "games#index"
  resources :secret_numbers, :only => [:new, :show]
  get '/games', to: 'games#index'
  get '/secret_numbers', to: 'secret_numbers#new'

  resources :rock_paper_scissors, :only => [:new, :show]
  get '/rock', to: 'rock_paper_scissors#new'
  get '/rocks', to: 'rock_paper_scissors#new'

end

08_Routes_Cont_Views/games_on_rails/app/controllers/concerns/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
	def new
	end	

	def show
		@choosen_number = params[:id].to_i
		@secret_number = rand(5)+1
	end	
end	

08_Routes_Cont_Views/games_on_rails/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

 
end

08_Routes_Cont_Views/games_on_rails/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
	def new
	end	

	def show
		@choosen_number = params[:id].to_i
		#@secret_number = rand(5)+1
		@throw = rand(3)+1
	end	
end	

08_Routes_Cont_Views/games_on_rails/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
	def new
	end	

	def show
		@choosen_number = params[:id].to_i
		@secret_number = rand(5)+1
		#@throw = rand(3)+1
	end	
end	

08_Routes_Cont_Views/games_on_rails/app/views/games/index.html.erb
<h1>Welcome to the Game Center!</h1>

<p>Choose a game below to get started:</p>

<br/>

<table>
  <tr>
    <td>
      <%=link_to image_tag("games/secret-number.jpg"), new_secret_number_path %>
      <h4>SECRET NUMBER</h4>
    </td>
    <td>
      <%=link_to image_tag("games/rock-paper-scissors.jpg"), new_rock_paper_scissor_path %>
      <h4>ROCK PAPER SCISSORS</h4>
    </td>
  </tr>
</table>