15_Lab_Session/solutions/Museum_App/config/routes.rb
MuseumApp::Application.routes.draw do
  root "paintings#index"
  get 'search', to: 'paintings#search'
  resources :paintings
  resources :museums
  resources :artists
end

15_Lab_Session/solutions/Museum_App/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :paintings
	has_many :museums, through: :paintings
end

15_Lab_Session/solutions/Museum_App/app/models/museum.rb
class Museum < ActiveRecord::Base
	has_many :paintings
	has_many :artists, through: :paintings
end

15_Lab_Session/solutions/Museum_App/app/models/painting.rb
class Painting < ActiveRecord::Base
  validates :title, :year, :style, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  belongs_to :museum
  belongs_to :artist

  def self.search_for(query)
    where('title LIKE :query', :query => "%#{query}%")
  end
end

15_Lab_Session/solutions/Museum_App/app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
	

  def index
  	@museums = Museum.all
  end

  def show
  	@museum = Museum.find(params[:id])
  end

  def new
    @museum = Museum.new
  end

  def create
    @museum = Museum.new(safe_museum_params)
    if @museum.save
      redirect_to @museum
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  private

  def safe_museum_params
    params.require('museum').permit(:name, :city)
  end

end
 

15_Lab_Session/solutions/Museum_App/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
	  before_action :load_painting, only: [:edit, :show, :update]

  def index
  	@paintings = params[:q] ? Painting.search_for(params[:q]) : Painting.all
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(safe_painting_params)
    if @painting.save
      redirect_to @painting
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @painting.update(safe_painting_params)
      redirect_to @painting
    else
      render 'edit'
    end
  end

  def show
  end

  private

  def safe_painting_params
    params.require('painting').permit(:title, :year, :style, :image, :museum_id)
  end

  def load_painting
    @painting = Painting.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash.now[:notice] = "Invalid Painting ID #{params[:id]}"
    redirect_to root_path
  end
end

15_Lab_Session/solutions/Museum_App/app/helpers/museums_helper.rb
module MuseumsHelper
end

15_Lab_Session/solutions/Museum_App/app/helpers/paintings_helper.rb
module PaintingsHelper
end

15_Lab_Session/solutions/Museum_App/app/views/paintings/_form.html.erb
<% if @painting.errors.any? %>
  <h2>There were errors saving your painting</h2>
  <ul>
    <% @painting.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @painting do |f| %>
  <fieldset>
    <div class='fields'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='fields'>
      <%= f.label :year %>
      <%= f.text_field :year %>
    </div>
    <div class='fields'>
  <%= f.label :style %>
  <%= f.select :style, [['Oil', "oil"],['Canvas','canvas'],['Water Color','water colors'], ['Fabric','fabric']] %>
    </div>
    <div class='fields'>
      <%= f.label :image %>
      <%= f.text_field :image %>
    </div>

    <div class='fields'>
      <%=f.label :museum %>
      <%= f.select :museum_id, Museum.all.collect {|museum| [ museum.name, museum.id] } %>
    </div>
  </fieldset>
  <%= f.submit %>
<% end %>

<br/>

15_Lab_Session/solutions/Museum_App/app/views/paintings/edit.html.erb
<h1>Edit The Painting</h1>
<%= image_tag @painting.image %>
<%= render 'form' %>

15_Lab_Session/solutions/Museum_App/app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>

<h3><%= link_to "+ Add New Painting", new_painting_path %></h3>


<%= form_tag "/", method: "GET" do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Search" %>
<% end %>

<br/><hr/>

<% if @paintings.any? %>

  <% @paintings.each do |painting| %>
    <section>
      <h3><b>Title</b>: <%= link_to painting.title, painting %></h3>
      <%= image_tag painting.image %>
      <p><b>Year</b>: <%= painting.year%></p>
      <p><b>Style</b>: <%= painting.style%></p>
      <p><b>Museum</b>: <%= link_to painting.museum.name, painting.museum %></p>

      <hr>
    </section>
  <% end %>

<% else %>

  <h4>Sorry, no paintings matched your query.</h4>

<% end %>

15_Lab_Session/solutions/Museum_App/app/views/paintings/new.html.erb
<h1>Add a New Painting</h1>
<%= render 'form' %>

15_Lab_Session/solutions/Museum_App/app/views/paintings/show.html.erb
<h1><%= @painting.title %></h1>
<p>Year: <%= @painting.year %></p>
<p>Style: <%= @painting.style%></p>
<%= image_tag @painting.image %>
<br/>
<%= link_to "Edit This Painting", edit_painting_path(@painting) %>
<br/><br/>